package main

const masterHTML = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Coverage Master Report</title>
    <style>
      /* Base reset */
      * {
        box-sizing: border-box;
        margin: 0;
        padding: 0;
      }
      body {
        font-family: sans-serif;
        line-height: 1.6;
        background: #f5f5f5;
        color: #333;
        padding: 2rem;
      }
      h1 {
        margin-bottom: 1rem;
        text-align: center;
        font-size: 1.75rem;
        color: #2c3e50;
      }
      /* Table container */
      .table-container {
        max-width: 960px;
        margin: 0 auto 2rem;
        overflow-x: auto;
        background: #fff;
        border-radius: 0.5rem;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      }
      table {
        width: 100%;
        border-collapse: collapse;
        min-width: 600px;
      }
      thead {
        background: #2c3e50;
        color: #fff;
      }
      th,
      td {
        padding: 0.75rem 1rem;
        text-align: left;
      }
      tbody tr:nth-child(odd) {
        background: #f9f9f9;
      }
      tbody tr:hover {
        background: #e1ecf4;
      }
      a {
        color: #2980b9;
        text-decoration: none;
      }
      a:hover {
        text-decoration: underline;
      }
      /* Footer */
      footer {
        text-align: center;
        font-size: 0.875rem;
        color: #666;
      }
      footer a {
        color: #666;
        text-decoration: none;
      }
      footer a:hover {
        text-decoration: underline;
      }
    </style>
  </head>

  <body>
    <h1>All Packages &amp; Targets of {{ .ProjectName }}</h1>

    <div class="table-container">
      <table>
        <thead>
          <tr>
            <th>Package Path</th>
            <th>Target</th>
          </tr>
        </thead>
        <tbody>
          {{- range .Entries }}
          <tr>
            <td>{{ .PkgPath }}</td>
            <td><a href="{{ .LinkFile }}">{{ .Target }}</a></td>
          </tr>
          {{- end }}
        </tbody>
      </table>
    </div>

    <footer>
      Generated by
      <a
        href="https://github.com/go-continuous-fuzz/go-continuous-fuzz"
        target="_blank"
      >
        go-continuous-fuzz
      </a>
    </footer>
  </body>
</html>
`

const targetHTML = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Coverage for {{ .Target }}</title>
    <style>
      /* Base reset */
      * {
        box-sizing: border-box;
        margin: 0;
        padding: 0;
      }
      body {
        font-family: sans-serif;
        line-height: 1.6;
        background: #f5f5f5;
        color: #333;
        padding: 2rem;
      }
      h1 {
        margin-bottom: 1rem;
        text-align: center;
        font-size: 1.75rem;
        color: #2c3e50;
      }
      /* Table container */
      .table-container {
        max-width: 960px;
        margin: 0 auto 2rem;
        overflow-x: auto;
        background: #fff;
        border-radius: 0.5rem;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      }
      table {
        width: 100%;
        border-collapse: collapse;
        min-width: 500px;
      }
      thead {
        background: #2c3e50;
        color: #fff;
      }
      th,
      td {
        padding: 0.75rem 1rem;
        text-align: left;
      }
      tbody tr:nth-child(odd) {
        background: #f9f9f9;
      }
      tbody tr:hover {
        background: #e1ecf4;
      }
      a {
        color: #2980b9;
        text-decoration: none;
      }
      a:hover {
        text-decoration: underline;
      }
      /* Footer */
      footer {
        text-align: center;
        font-size: 0.875rem;
        color: #666;
      }
      footer a {
        color: #666;
        text-decoration: none;
      }
      footer a:hover {
        text-decoration: underline;
      }
    </style>
  </head>

  <body>
    <h1>Coverage History for {{ .Target }}</h1>

    <div class="table-container">
      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Coverage (%)</th>
            <th>Report</th>
          </tr>
        </thead>
        <tbody>
          {{- range .History }}
          <tr>
            <td>{{ .Date }}</td>
            <td>{{ .Coverage }}</td>
            <td><a href="{{ .ReportPath }}" target="_blank">View</a></td>
          </tr>
          {{- end }}
        </tbody>
      </table>
    </div>

    <footer>
      Generated by
      <a
        href="https://github.com/go-continuous-fuzz/go-continuous-fuzz"
        target="_blank"
      >
        go-continuous-fuzz
      </a>
    </footer>
  </body>
</html>
`
