apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-continuous-fuzz-pvc
  namespace: go-continuous-fuzz-ns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
